services:
  db:
    image: postgres:17-alpine
    container_name: musicmakers-db
    environment:
      - POSTGRES_DB=musicmakers_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
     - "5433:5432"
    volumes:
      - postgres_data_new:/var/lib/postgresql/data
    networks:
      - musicmakers-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: .
    container_name: musicmakers-backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_NAME=musicmakers_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_WEB_RESOURCES_STATIC_LOCATIONS=classpath:/static/,file:/app/resources/static/
    volumes:
      - ./src/main/resources/static:/app/resources/static
    depends_on:
      db:
        condition: service_healthy
    networks:
      - musicmakers-network