version: '3.8'

services:
  # Serviço do Banco de Dados
  db:
    image: postgres:17-alpine
    container_name: musicmakers-db
    environment:
      - POSTGRES_DB=musicmakers_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - musicmakers-network

  # Serviço do Backend (Seu Projeto)
  backend:
    build: .
    container_name: musicmakers-backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_NAME=musicmakers_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
    networks:
      - musicmakers-network

volumes:
  postgres_data:

networks:
  musicmakers-network: